CREATE DATABASE IF NOT EXISTS quick_admin;

USE quick_admin;

DROP TABLE IF EXISTS `auth_permission`;
CREATE TABLE `auth_permission`
(
    `id`          BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
    `permission`  VARCHAR(100) DEFAULT NULL COMMENT '权限',
    `description` VARCHAR(100) DEFAULT NULL COMMENT '描述',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT = '权限表';

DROP TABLE IF EXISTS `auth_user`;
CREATE TABLE `auth_user`
(
    `id`       BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `username` VARCHAR(25) DEFAULT '' COMMENT '用户名',
    `password` VARCHAR(50) DEFAULT '' COMMENT '密码',
    `email`    VARCHAR(50) DEFAULT '' COMMENT '邮箱',
    `gender`   BIT(2)      DEFAULT B'10' COMMENT '性别：0 -> 男; 1-> 女; 2 -> 未知',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT = '用户表';

DROP TABLE IF EXISTS `auth_role`;
CREATE TABLE `auth_role`
(
    `id`   BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `role` VARCHAR(25) DEFAULT '' COMMENT '角色',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT = '角色表';

DROP TABLE IF EXISTS `auth_user_role`;
CREATE TABLE `auth_user_role`
(
    `id`      BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `user_id` BIGINT DEFAULT NULL COMMENT '用户 ID',
    `role_id` BIGINT DEFAULT NULL COMMENT '角色 ID',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT = '用户角色关联表';

DROP TABLE IF EXISTS `auth_role_permission`;
CREATE TABLE `auth_role_permission`
(
    `id`            BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `role_id`       BIGINT DEFAULT NULL COMMENT '角色 ID',
    `permission_id` BIGINT DEFAULT NULL COMMENT '权限 ID',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT = '角色权限关联表';
